name: Java at_client CI

on:
  push:
    branches:
      - trunk
    paths:
      - at_client/**
  pull_request:
    branches:
      - trunk
    paths:
      - at_client/**

jobs:
  test-and-build:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 and maven cache
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: "MAVEN_USERNAME" # env variable for username in deploy
          server-password: "MAVEN_PASSWORD" # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: "GPG_PASSPHRASE" # env variable for GPG private key passphrase
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Test and Build with Maven
        run: mvn --batch-mode --update-snapshots clean install
