name: Java at_client CI

on:
  push:
    branches:
      - trunk
    paths:
      - at_client/**
  pull_request:
    branches:
      - trunk
    paths:
      - at_client/**

jobs:
  build-and-test:
    defaults:
      run:
        working-directory: at_client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8 and maven cache
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven
      - name: Build clean and run unit tests
        run: mvn --batch-mode --update-snapshots clean test -DskipIntegrationTests=true
      - name: Run integration tests
        run: mvn --batch-mode verify -DskipUnitTests=true
      - name: Generate build outputs
        run: mvn --batch-mode install -DskipTests=true
      # TODO Artefact version management, publishing to maven central